#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hiến_máu
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLDKHienMau")]
	public partial class QLDKHienMauDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertChienDich(ChienDich instance);
    partial void UpdateChienDich(ChienDich instance);
    partial void DeleteChienDich(ChienDich instance);
    partial void InsertPhieuDK(PhieuDK instance);
    partial void UpdatePhieuDK(PhieuDK instance);
    partial void DeletePhieuDK(PhieuDK instance);
    partial void InsertHoSoDK(HoSoDK instance);
    partial void UpdateHoSoDK(HoSoDK instance);
    partial void DeleteHoSoDK(HoSoDK instance);
    partial void InsertPhieuKQ(PhieuKQ instance);
    partial void UpdatePhieuKQ(PhieuKQ instance);
    partial void DeletePhieuKQ(PhieuKQ instance);
    partial void InserttblLogin(tblLogin instance);
    partial void UpdatetblLogin(tblLogin instance);
    partial void DeletetblLogin(tblLogin instance);
    #endregion
		
		public QLDKHienMauDataContext() : 
				base(global::Hiến_máu.Properties.Settings.Default.QLDKHienMauConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public QLDKHienMauDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDKHienMauDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDKHienMauDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDKHienMauDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<ChienDich> ChienDiches
		{
			get
			{
				return this.GetTable<ChienDich>();
			}
		}
		
		public System.Data.Linq.Table<PhieuDK> PhieuDKs
		{
			get
			{
				return this.GetTable<PhieuDK>();
			}
		}
		
		public System.Data.Linq.Table<HoSoDK> HoSoDKs
		{
			get
			{
				return this.GetTable<HoSoDK>();
			}
		}
		
		public System.Data.Linq.Table<PhieuKQ> PhieuKQs
		{
			get
			{
				return this.GetTable<PhieuKQ>();
			}
		}
		
		public System.Data.Linq.Table<tblLogin> tblLogins
		{
			get
			{
				return this.GetTable<tblLogin>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChienDich")]
	public partial class ChienDich : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mscd;
		
		private string _tenChienDich;
		
		private string _slogan__logo;
		
		private System.DateTime _ngayThang;
		
		private string _thoiGian;
		
		private string _diaChi;
		
		private string _diaChiEmail;
		
		private string _web;
		
		private EntitySet<PhieuDK> _PhieuDKs;
		
		private EntitySet<PhieuKQ> _PhieuKQs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmscdChanging(int value);
    partial void OnmscdChanged();
    partial void OntenChienDichChanging(string value);
    partial void OntenChienDichChanged();
    partial void Onslogan__logoChanging(string value);
    partial void Onslogan__logoChanged();
    partial void OnngayThangChanging(System.DateTime value);
    partial void OnngayThangChanged();
    partial void OnthoiGianChanging(string value);
    partial void OnthoiGianChanged();
    partial void OndiaChiChanging(string value);
    partial void OndiaChiChanged();
    partial void OndiaChiEmailChanging(string value);
    partial void OndiaChiEmailChanged();
    partial void OnwebChanging(string value);
    partial void OnwebChanged();
    #endregion
		
		public ChienDich()
		{
			this._PhieuDKs = new EntitySet<PhieuDK>(new Action<PhieuDK>(this.attach_PhieuDKs), new Action<PhieuDK>(this.detach_PhieuDKs));
			this._PhieuKQs = new EntitySet<PhieuKQ>(new Action<PhieuKQ>(this.attach_PhieuKQs), new Action<PhieuKQ>(this.detach_PhieuKQs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mscd", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mscd
		{
			get
			{
				return this._mscd;
			}
			set
			{
				if ((this._mscd != value))
				{
					this.OnmscdChanging(value);
					this.SendPropertyChanging();
					this._mscd = value;
					this.SendPropertyChanged("mscd");
					this.OnmscdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenChienDich", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string tenChienDich
		{
			get
			{
				return this._tenChienDich;
			}
			set
			{
				if ((this._tenChienDich != value))
				{
					this.OntenChienDichChanging(value);
					this.SendPropertyChanging();
					this._tenChienDich = value;
					this.SendPropertyChanged("tenChienDich");
					this.OntenChienDichChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[slogan, logo]", Storage="_slogan__logo", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string slogan__logo
		{
			get
			{
				return this._slogan__logo;
			}
			set
			{
				if ((this._slogan__logo != value))
				{
					this.Onslogan__logoChanging(value);
					this.SendPropertyChanging();
					this._slogan__logo = value;
					this.SendPropertyChanged("slogan__logo");
					this.Onslogan__logoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayThang", DbType="Date NOT NULL")]
		public System.DateTime ngayThang
		{
			get
			{
				return this._ngayThang;
			}
			set
			{
				if ((this._ngayThang != value))
				{
					this.OnngayThangChanging(value);
					this.SendPropertyChanging();
					this._ngayThang = value;
					this.SendPropertyChanged("ngayThang");
					this.OnngayThangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thoiGian", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string thoiGian
		{
			get
			{
				return this._thoiGian;
			}
			set
			{
				if ((this._thoiGian != value))
				{
					this.OnthoiGianChanging(value);
					this.SendPropertyChanging();
					this._thoiGian = value;
					this.SendPropertyChanged("thoiGian");
					this.OnthoiGianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChi", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string diaChi
		{
			get
			{
				return this._diaChi;
			}
			set
			{
				if ((this._diaChi != value))
				{
					this.OndiaChiChanging(value);
					this.SendPropertyChanging();
					this._diaChi = value;
					this.SendPropertyChanged("diaChi");
					this.OndiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaChiEmail", DbType="NVarChar(MAX)")]
		public string diaChiEmail
		{
			get
			{
				return this._diaChiEmail;
			}
			set
			{
				if ((this._diaChiEmail != value))
				{
					this.OndiaChiEmailChanging(value);
					this.SendPropertyChanging();
					this._diaChiEmail = value;
					this.SendPropertyChanged("diaChiEmail");
					this.OndiaChiEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_web", DbType="NVarChar(50)")]
		public string web
		{
			get
			{
				return this._web;
			}
			set
			{
				if ((this._web != value))
				{
					this.OnwebChanging(value);
					this.SendPropertyChanging();
					this._web = value;
					this.SendPropertyChanged("web");
					this.OnwebChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChienDich_PhieuDK", Storage="_PhieuDKs", ThisKey="mscd", OtherKey="mscd")]
		public EntitySet<PhieuDK> PhieuDKs
		{
			get
			{
				return this._PhieuDKs;
			}
			set
			{
				this._PhieuDKs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChienDich_PhieuKQ", Storage="_PhieuKQs", ThisKey="mscd", OtherKey="mscd")]
		public EntitySet<PhieuKQ> PhieuKQs
		{
			get
			{
				return this._PhieuKQs;
			}
			set
			{
				this._PhieuKQs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuDKs(PhieuDK entity)
		{
			this.SendPropertyChanging();
			entity.ChienDich = this;
		}
		
		private void detach_PhieuDKs(PhieuDK entity)
		{
			this.SendPropertyChanging();
			entity.ChienDich = null;
		}
		
		private void attach_PhieuKQs(PhieuKQ entity)
		{
			this.SendPropertyChanging();
			entity.ChienDich = this;
		}
		
		private void detach_PhieuKQs(PhieuKQ entity)
		{
			this.SendPropertyChanging();
			entity.ChienDich = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuDK")]
	public partial class PhieuDK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mscd;
		
		private int _mspDangKy;
		
		private string _GioDkHienMau;
		
		private System.DateTime _ngayDKHienMau;
		
		private System.DateTime _ngayHienMauTruoc;
		
		private string _diaDiemDKHienMau;
		
		private string _loaiHienMau;
		
		private string _tiemVaccineCovid19;
		
		private string _sdtNguoiThan;
		
		private string _trangThaiDK;
		
		private int _mshs;
		
		private EntitySet<PhieuKQ> _PhieuKQs;
		
		private EntityRef<ChienDich> _ChienDich;
		
		private EntityRef<HoSoDK> _HoSoDK;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmscdChanging(int value);
    partial void OnmscdChanged();
    partial void OnmspDangKyChanging(int value);
    partial void OnmspDangKyChanged();
    partial void OnGioDkHienMauChanging(string value);
    partial void OnGioDkHienMauChanged();
    partial void OnngayDKHienMauChanging(System.DateTime value);
    partial void OnngayDKHienMauChanged();
    partial void OnngayHienMauTruocChanging(System.DateTime value);
    partial void OnngayHienMauTruocChanged();
    partial void OndiaDiemDKHienMauChanging(string value);
    partial void OndiaDiemDKHienMauChanged();
    partial void OnloaiHienMauChanging(string value);
    partial void OnloaiHienMauChanged();
    partial void OntiemVaccineCovid19Changing(string value);
    partial void OntiemVaccineCovid19Changed();
    partial void OnsdtNguoiThanChanging(string value);
    partial void OnsdtNguoiThanChanged();
    partial void OntrangThaiDKChanging(string value);
    partial void OntrangThaiDKChanged();
    partial void OnmshsChanging(int value);
    partial void OnmshsChanged();
    #endregion
		
		public PhieuDK()
		{
			this._PhieuKQs = new EntitySet<PhieuKQ>(new Action<PhieuKQ>(this.attach_PhieuKQs), new Action<PhieuKQ>(this.detach_PhieuKQs));
			this._ChienDich = default(EntityRef<ChienDich>);
			this._HoSoDK = default(EntityRef<HoSoDK>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mscd", DbType="Int NOT NULL")]
		public int mscd
		{
			get
			{
				return this._mscd;
			}
			set
			{
				if ((this._mscd != value))
				{
					if (this._ChienDich.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmscdChanging(value);
					this.SendPropertyChanging();
					this._mscd = value;
					this.SendPropertyChanged("mscd");
					this.OnmscdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mspDangKy", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mspDangKy
		{
			get
			{
				return this._mspDangKy;
			}
			set
			{
				if ((this._mspDangKy != value))
				{
					this.OnmspDangKyChanging(value);
					this.SendPropertyChanging();
					this._mspDangKy = value;
					this.SendPropertyChanged("mspDangKy");
					this.OnmspDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GioDkHienMau", DbType="VarChar(7) NOT NULL", CanBeNull=false)]
		public string GioDkHienMau
		{
			get
			{
				return this._GioDkHienMau;
			}
			set
			{
				if ((this._GioDkHienMau != value))
				{
					this.OnGioDkHienMauChanging(value);
					this.SendPropertyChanging();
					this._GioDkHienMau = value;
					this.SendPropertyChanged("GioDkHienMau");
					this.OnGioDkHienMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayDKHienMau", DbType="Date NOT NULL")]
		public System.DateTime ngayDKHienMau
		{
			get
			{
				return this._ngayDKHienMau;
			}
			set
			{
				if ((this._ngayDKHienMau != value))
				{
					this.OnngayDKHienMauChanging(value);
					this.SendPropertyChanging();
					this._ngayDKHienMau = value;
					this.SendPropertyChanged("ngayDKHienMau");
					this.OnngayDKHienMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayHienMauTruoc", DbType="Date NOT NULL")]
		public System.DateTime ngayHienMauTruoc
		{
			get
			{
				return this._ngayHienMauTruoc;
			}
			set
			{
				if ((this._ngayHienMauTruoc != value))
				{
					this.OnngayHienMauTruocChanging(value);
					this.SendPropertyChanging();
					this._ngayHienMauTruoc = value;
					this.SendPropertyChanged("ngayHienMauTruoc");
					this.OnngayHienMauTruocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diaDiemDKHienMau", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string diaDiemDKHienMau
		{
			get
			{
				return this._diaDiemDKHienMau;
			}
			set
			{
				if ((this._diaDiemDKHienMau != value))
				{
					this.OndiaDiemDKHienMauChanging(value);
					this.SendPropertyChanging();
					this._diaDiemDKHienMau = value;
					this.SendPropertyChanged("diaDiemDKHienMau");
					this.OndiaDiemDKHienMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiHienMau", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string loaiHienMau
		{
			get
			{
				return this._loaiHienMau;
			}
			set
			{
				if ((this._loaiHienMau != value))
				{
					this.OnloaiHienMauChanging(value);
					this.SendPropertyChanging();
					this._loaiHienMau = value;
					this.SendPropertyChanged("loaiHienMau");
					this.OnloaiHienMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tiemVaccineCovid19", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string tiemVaccineCovid19
		{
			get
			{
				return this._tiemVaccineCovid19;
			}
			set
			{
				if ((this._tiemVaccineCovid19 != value))
				{
					this.OntiemVaccineCovid19Changing(value);
					this.SendPropertyChanging();
					this._tiemVaccineCovid19 = value;
					this.SendPropertyChanged("tiemVaccineCovid19");
					this.OntiemVaccineCovid19Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdtNguoiThan", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string sdtNguoiThan
		{
			get
			{
				return this._sdtNguoiThan;
			}
			set
			{
				if ((this._sdtNguoiThan != value))
				{
					this.OnsdtNguoiThanChanging(value);
					this.SendPropertyChanging();
					this._sdtNguoiThan = value;
					this.SendPropertyChanged("sdtNguoiThan");
					this.OnsdtNguoiThanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trangThaiDK", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string trangThaiDK
		{
			get
			{
				return this._trangThaiDK;
			}
			set
			{
				if ((this._trangThaiDK != value))
				{
					this.OntrangThaiDKChanging(value);
					this.SendPropertyChanging();
					this._trangThaiDK = value;
					this.SendPropertyChanged("trangThaiDK");
					this.OntrangThaiDKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mshs", DbType="Int NOT NULL")]
		public int mshs
		{
			get
			{
				return this._mshs;
			}
			set
			{
				if ((this._mshs != value))
				{
					if (this._HoSoDK.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmshsChanging(value);
					this.SendPropertyChanging();
					this._mshs = value;
					this.SendPropertyChanged("mshs");
					this.OnmshsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuDK_PhieuKQ", Storage="_PhieuKQs", ThisKey="mspDangKy", OtherKey="mspDangKy")]
		public EntitySet<PhieuKQ> PhieuKQs
		{
			get
			{
				return this._PhieuKQs;
			}
			set
			{
				this._PhieuKQs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChienDich_PhieuDK", Storage="_ChienDich", ThisKey="mscd", OtherKey="mscd", IsForeignKey=true)]
		public ChienDich ChienDich
		{
			get
			{
				return this._ChienDich.Entity;
			}
			set
			{
				ChienDich previousValue = this._ChienDich.Entity;
				if (((previousValue != value) 
							|| (this._ChienDich.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChienDich.Entity = null;
						previousValue.PhieuDKs.Remove(this);
					}
					this._ChienDich.Entity = value;
					if ((value != null))
					{
						value.PhieuDKs.Add(this);
						this._mscd = value.mscd;
					}
					else
					{
						this._mscd = default(int);
					}
					this.SendPropertyChanged("ChienDich");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoSoDK_PhieuDK", Storage="_HoSoDK", ThisKey="mshs", OtherKey="mshs", IsForeignKey=true)]
		public HoSoDK HoSoDK
		{
			get
			{
				return this._HoSoDK.Entity;
			}
			set
			{
				HoSoDK previousValue = this._HoSoDK.Entity;
				if (((previousValue != value) 
							|| (this._HoSoDK.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoSoDK.Entity = null;
						previousValue.PhieuDKs.Remove(this);
					}
					this._HoSoDK.Entity = value;
					if ((value != null))
					{
						value.PhieuDKs.Add(this);
						this._mshs = value.mshs;
					}
					else
					{
						this._mshs = default(int);
					}
					this.SendPropertyChanged("HoSoDK");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuKQs(PhieuKQ entity)
		{
			this.SendPropertyChanging();
			entity.PhieuDK = this;
		}
		
		private void detach_PhieuKQs(PhieuKQ entity)
		{
			this.SendPropertyChanging();
			entity.PhieuDK = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoSoDK")]
	public partial class HoSoDK : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mshs;
		
		private string _hoTen;
		
		private System.DateTime _ntns;
		
		private string _gioitinh;
		
		private string _dclh;
		
		private string _sdtlh;
		
		private string _DCemail;
		
		private string _nhommau;
		
		private System.Nullable<int> _IDAccount;
		
		private EntitySet<PhieuDK> _PhieuDKs;
		
		private EntitySet<PhieuKQ> _PhieuKQs;
		
		private EntityRef<tblLogin> _tblLogin;
		
		private EntityRef<tblLogin> _tblLogin1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmshsChanging(int value);
    partial void OnmshsChanged();
    partial void OnhoTenChanging(string value);
    partial void OnhoTenChanged();
    partial void OnntnsChanging(System.DateTime value);
    partial void OnntnsChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OndclhChanging(string value);
    partial void OndclhChanged();
    partial void OnsdtlhChanging(string value);
    partial void OnsdtlhChanged();
    partial void OnDCemailChanging(string value);
    partial void OnDCemailChanged();
    partial void OnnhommauChanging(string value);
    partial void OnnhommauChanged();
    partial void OnIDAccountChanging(System.Nullable<int> value);
    partial void OnIDAccountChanged();
    #endregion
		
		public HoSoDK()
		{
			this._PhieuDKs = new EntitySet<PhieuDK>(new Action<PhieuDK>(this.attach_PhieuDKs), new Action<PhieuDK>(this.detach_PhieuDKs));
			this._PhieuKQs = new EntitySet<PhieuKQ>(new Action<PhieuKQ>(this.attach_PhieuKQs), new Action<PhieuKQ>(this.detach_PhieuKQs));
			this._tblLogin = default(EntityRef<tblLogin>);
			this._tblLogin1 = default(EntityRef<tblLogin>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mshs", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mshs
		{
			get
			{
				return this._mshs;
			}
			set
			{
				if ((this._mshs != value))
				{
					this.OnmshsChanging(value);
					this.SendPropertyChanging();
					this._mshs = value;
					this.SendPropertyChanged("mshs");
					this.OnmshsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_hoTen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string hoTen
		{
			get
			{
				return this._hoTen;
			}
			set
			{
				if ((this._hoTen != value))
				{
					this.OnhoTenChanging(value);
					this.SendPropertyChanging();
					this._hoTen = value;
					this.SendPropertyChanged("hoTen");
					this.OnhoTenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ntns", DbType="Date NOT NULL")]
		public System.DateTime ntns
		{
			get
			{
				return this._ntns;
			}
			set
			{
				if ((this._ntns != value))
				{
					this.OnntnsChanging(value);
					this.SendPropertyChanging();
					this._ntns = value;
					this.SendPropertyChanged("ntns");
					this.OnntnsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dclh", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string dclh
		{
			get
			{
				return this._dclh;
			}
			set
			{
				if ((this._dclh != value))
				{
					this.OndclhChanging(value);
					this.SendPropertyChanging();
					this._dclh = value;
					this.SendPropertyChanged("dclh");
					this.OndclhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sdtlh", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string sdtlh
		{
			get
			{
				return this._sdtlh;
			}
			set
			{
				if ((this._sdtlh != value))
				{
					this.OnsdtlhChanging(value);
					this.SendPropertyChanging();
					this._sdtlh = value;
					this.SendPropertyChanged("sdtlh");
					this.OnsdtlhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DCemail", DbType="NVarChar(MAX)")]
		public string DCemail
		{
			get
			{
				return this._DCemail;
			}
			set
			{
				if ((this._DCemail != value))
				{
					this.OnDCemailChanging(value);
					this.SendPropertyChanging();
					this._DCemail = value;
					this.SendPropertyChanged("DCemail");
					this.OnDCemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nhommau", DbType="NVarChar(10)")]
		public string nhommau
		{
			get
			{
				return this._nhommau;
			}
			set
			{
				if ((this._nhommau != value))
				{
					this.OnnhommauChanging(value);
					this.SendPropertyChanging();
					this._nhommau = value;
					this.SendPropertyChanged("nhommau");
					this.OnnhommauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAccount", DbType="Int")]
		public System.Nullable<int> IDAccount
		{
			get
			{
				return this._IDAccount;
			}
			set
			{
				if ((this._IDAccount != value))
				{
					if ((this._tblLogin.HasLoadedOrAssignedValue || this._tblLogin1.HasLoadedOrAssignedValue))
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDAccountChanging(value);
					this.SendPropertyChanging();
					this._IDAccount = value;
					this.SendPropertyChanged("IDAccount");
					this.OnIDAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoSoDK_PhieuDK", Storage="_PhieuDKs", ThisKey="mshs", OtherKey="mshs")]
		public EntitySet<PhieuDK> PhieuDKs
		{
			get
			{
				return this._PhieuDKs;
			}
			set
			{
				this._PhieuDKs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoSoDK_PhieuKQ", Storage="_PhieuKQs", ThisKey="mshs", OtherKey="mshs")]
		public EntitySet<PhieuKQ> PhieuKQs
		{
			get
			{
				return this._PhieuKQs;
			}
			set
			{
				this._PhieuKQs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLogin_HoSoDK", Storage="_tblLogin", ThisKey="IDAccount", OtherKey="IDAccount", IsForeignKey=true)]
		public tblLogin tblLogin
		{
			get
			{
				return this._tblLogin.Entity;
			}
			set
			{
				tblLogin previousValue = this._tblLogin.Entity;
				if (((previousValue != value) 
							|| (this._tblLogin.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblLogin.Entity = null;
						previousValue.HoSoDKs.Remove(this);
					}
					this._tblLogin.Entity = value;
					if ((value != null))
					{
						value.HoSoDKs.Add(this);
						this._IDAccount = value.IDAccount;
					}
					else
					{
						this._IDAccount = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblLogin");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLogin_HoSoDK1", Storage="_tblLogin1", ThisKey="IDAccount", OtherKey="IDAccount", IsForeignKey=true)]
		public tblLogin tblLogin1
		{
			get
			{
				return this._tblLogin1.Entity;
			}
			set
			{
				tblLogin previousValue = this._tblLogin1.Entity;
				if (((previousValue != value) 
							|| (this._tblLogin1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblLogin1.Entity = null;
						previousValue.HoSoDKs1.Remove(this);
					}
					this._tblLogin1.Entity = value;
					if ((value != null))
					{
						value.HoSoDKs1.Add(this);
						this._IDAccount = value.IDAccount;
					}
					else
					{
						this._IDAccount = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblLogin1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PhieuDKs(PhieuDK entity)
		{
			this.SendPropertyChanging();
			entity.HoSoDK = this;
		}
		
		private void detach_PhieuDKs(PhieuDK entity)
		{
			this.SendPropertyChanging();
			entity.HoSoDK = null;
		}
		
		private void attach_PhieuKQs(PhieuKQ entity)
		{
			this.SendPropertyChanging();
			entity.HoSoDK = this;
		}
		
		private void detach_PhieuKQs(PhieuKQ entity)
		{
			this.SendPropertyChanging();
			entity.HoSoDK = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PhieuKQ")]
	public partial class PhieuKQ : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mspKetQua;
		
		private int _mspDangKy;
		
		private System.DateTime _ngayThucSuHienMau;
		
		private string _soLuongMauDaHien;
		
		private string _loaiHienMauThucSu;
		
		private string _tinhTrangHienMau;
		
		private string _tinhTrangSucKhoe;
		
		private string _ghiChu;
		
		private int _mscd;
		
		private System.Nullable<int> _mshs;
		
		private EntityRef<HoSoDK> _HoSoDK;
		
		private EntityRef<ChienDich> _ChienDich;
		
		private EntityRef<PhieuDK> _PhieuDK;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmspKetQuaChanging(int value);
    partial void OnmspKetQuaChanged();
    partial void OnmspDangKyChanging(int value);
    partial void OnmspDangKyChanged();
    partial void OnngayThucSuHienMauChanging(System.DateTime value);
    partial void OnngayThucSuHienMauChanged();
    partial void OnsoLuongMauDaHienChanging(string value);
    partial void OnsoLuongMauDaHienChanged();
    partial void OnloaiHienMauThucSuChanging(string value);
    partial void OnloaiHienMauThucSuChanged();
    partial void OntinhTrangHienMauChanging(string value);
    partial void OntinhTrangHienMauChanged();
    partial void OntinhTrangSucKhoeChanging(string value);
    partial void OntinhTrangSucKhoeChanged();
    partial void OnghiChuChanging(string value);
    partial void OnghiChuChanged();
    partial void OnmscdChanging(int value);
    partial void OnmscdChanged();
    partial void OnmshsChanging(System.Nullable<int> value);
    partial void OnmshsChanged();
    #endregion
		
		public PhieuKQ()
		{
			this._HoSoDK = default(EntityRef<HoSoDK>);
			this._ChienDich = default(EntityRef<ChienDich>);
			this._PhieuDK = default(EntityRef<PhieuDK>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mspKetQua", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mspKetQua
		{
			get
			{
				return this._mspKetQua;
			}
			set
			{
				if ((this._mspKetQua != value))
				{
					this.OnmspKetQuaChanging(value);
					this.SendPropertyChanging();
					this._mspKetQua = value;
					this.SendPropertyChanged("mspKetQua");
					this.OnmspKetQuaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mspDangKy", DbType="Int NOT NULL")]
		public int mspDangKy
		{
			get
			{
				return this._mspDangKy;
			}
			set
			{
				if ((this._mspDangKy != value))
				{
					if (this._PhieuDK.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmspDangKyChanging(value);
					this.SendPropertyChanging();
					this._mspDangKy = value;
					this.SendPropertyChanged("mspDangKy");
					this.OnmspDangKyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngayThucSuHienMau", DbType="Date NOT NULL")]
		public System.DateTime ngayThucSuHienMau
		{
			get
			{
				return this._ngayThucSuHienMau;
			}
			set
			{
				if ((this._ngayThucSuHienMau != value))
				{
					this.OnngayThucSuHienMauChanging(value);
					this.SendPropertyChanging();
					this._ngayThucSuHienMau = value;
					this.SendPropertyChanged("ngayThucSuHienMau");
					this.OnngayThucSuHienMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soLuongMauDaHien", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string soLuongMauDaHien
		{
			get
			{
				return this._soLuongMauDaHien;
			}
			set
			{
				if ((this._soLuongMauDaHien != value))
				{
					this.OnsoLuongMauDaHienChanging(value);
					this.SendPropertyChanging();
					this._soLuongMauDaHien = value;
					this.SendPropertyChanged("soLuongMauDaHien");
					this.OnsoLuongMauDaHienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_loaiHienMauThucSu", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string loaiHienMauThucSu
		{
			get
			{
				return this._loaiHienMauThucSu;
			}
			set
			{
				if ((this._loaiHienMauThucSu != value))
				{
					this.OnloaiHienMauThucSuChanging(value);
					this.SendPropertyChanging();
					this._loaiHienMauThucSu = value;
					this.SendPropertyChanged("loaiHienMauThucSu");
					this.OnloaiHienMauThucSuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhTrangHienMau", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string tinhTrangHienMau
		{
			get
			{
				return this._tinhTrangHienMau;
			}
			set
			{
				if ((this._tinhTrangHienMau != value))
				{
					this.OntinhTrangHienMauChanging(value);
					this.SendPropertyChanging();
					this._tinhTrangHienMau = value;
					this.SendPropertyChanged("tinhTrangHienMau");
					this.OntinhTrangHienMauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhTrangSucKhoe", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string tinhTrangSucKhoe
		{
			get
			{
				return this._tinhTrangSucKhoe;
			}
			set
			{
				if ((this._tinhTrangSucKhoe != value))
				{
					this.OntinhTrangSucKhoeChanging(value);
					this.SendPropertyChanging();
					this._tinhTrangSucKhoe = value;
					this.SendPropertyChanged("tinhTrangSucKhoe");
					this.OntinhTrangSucKhoeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghiChu", DbType="NVarChar(MAX)")]
		public string ghiChu
		{
			get
			{
				return this._ghiChu;
			}
			set
			{
				if ((this._ghiChu != value))
				{
					this.OnghiChuChanging(value);
					this.SendPropertyChanging();
					this._ghiChu = value;
					this.SendPropertyChanged("ghiChu");
					this.OnghiChuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mscd", DbType="Int NOT NULL")]
		public int mscd
		{
			get
			{
				return this._mscd;
			}
			set
			{
				if ((this._mscd != value))
				{
					if (this._ChienDich.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmscdChanging(value);
					this.SendPropertyChanging();
					this._mscd = value;
					this.SendPropertyChanged("mscd");
					this.OnmscdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mshs", DbType="Int")]
		public System.Nullable<int> mshs
		{
			get
			{
				return this._mshs;
			}
			set
			{
				if ((this._mshs != value))
				{
					if (this._HoSoDK.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmshsChanging(value);
					this.SendPropertyChanging();
					this._mshs = value;
					this.SendPropertyChanged("mshs");
					this.OnmshsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoSoDK_PhieuKQ", Storage="_HoSoDK", ThisKey="mshs", OtherKey="mshs", IsForeignKey=true)]
		public HoSoDK HoSoDK
		{
			get
			{
				return this._HoSoDK.Entity;
			}
			set
			{
				HoSoDK previousValue = this._HoSoDK.Entity;
				if (((previousValue != value) 
							|| (this._HoSoDK.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoSoDK.Entity = null;
						previousValue.PhieuKQs.Remove(this);
					}
					this._HoSoDK.Entity = value;
					if ((value != null))
					{
						value.PhieuKQs.Add(this);
						this._mshs = value.mshs;
					}
					else
					{
						this._mshs = default(Nullable<int>);
					}
					this.SendPropertyChanged("HoSoDK");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChienDich_PhieuKQ", Storage="_ChienDich", ThisKey="mscd", OtherKey="mscd", IsForeignKey=true)]
		public ChienDich ChienDich
		{
			get
			{
				return this._ChienDich.Entity;
			}
			set
			{
				ChienDich previousValue = this._ChienDich.Entity;
				if (((previousValue != value) 
							|| (this._ChienDich.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChienDich.Entity = null;
						previousValue.PhieuKQs.Remove(this);
					}
					this._ChienDich.Entity = value;
					if ((value != null))
					{
						value.PhieuKQs.Add(this);
						this._mscd = value.mscd;
					}
					else
					{
						this._mscd = default(int);
					}
					this.SendPropertyChanged("ChienDich");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PhieuDK_PhieuKQ", Storage="_PhieuDK", ThisKey="mspDangKy", OtherKey="mspDangKy", IsForeignKey=true)]
		public PhieuDK PhieuDK
		{
			get
			{
				return this._PhieuDK.Entity;
			}
			set
			{
				PhieuDK previousValue = this._PhieuDK.Entity;
				if (((previousValue != value) 
							|| (this._PhieuDK.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PhieuDK.Entity = null;
						previousValue.PhieuKQs.Remove(this);
					}
					this._PhieuDK.Entity = value;
					if ((value != null))
					{
						value.PhieuKQs.Add(this);
						this._mspDangKy = value.mspDangKy;
					}
					else
					{
						this._mspDangKy = default(int);
					}
					this.SendPropertyChanged("PhieuDK");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblLogin")]
	public partial class tblLogin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IDAccount;
		
		private string _Username;
		
		private string _Password;
		
		private int _IDRole;
		
		private EntitySet<HoSoDK> _HoSoDKs;
		
		private EntitySet<HoSoDK> _HoSoDKs1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDAccountChanging(int value);
    partial void OnIDAccountChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnIDRoleChanging(int value);
    partial void OnIDRoleChanged();
    #endregion
		
		public tblLogin()
		{
			this._HoSoDKs = new EntitySet<HoSoDK>(new Action<HoSoDK>(this.attach_HoSoDKs), new Action<HoSoDK>(this.detach_HoSoDKs));
			this._HoSoDKs1 = new EntitySet<HoSoDK>(new Action<HoSoDK>(this.attach_HoSoDKs1), new Action<HoSoDK>(this.detach_HoSoDKs1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDAccount", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IDAccount
		{
			get
			{
				return this._IDAccount;
			}
			set
			{
				if ((this._IDAccount != value))
				{
					this.OnIDAccountChanging(value);
					this.SendPropertyChanging();
					this._IDAccount = value;
					this.SendPropertyChanged("IDAccount");
					this.OnIDAccountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDRole", DbType="Int NOT NULL")]
		public int IDRole
		{
			get
			{
				return this._IDRole;
			}
			set
			{
				if ((this._IDRole != value))
				{
					this.OnIDRoleChanging(value);
					this.SendPropertyChanging();
					this._IDRole = value;
					this.SendPropertyChanged("IDRole");
					this.OnIDRoleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLogin_HoSoDK", Storage="_HoSoDKs", ThisKey="IDAccount", OtherKey="IDAccount")]
		public EntitySet<HoSoDK> HoSoDKs
		{
			get
			{
				return this._HoSoDKs;
			}
			set
			{
				this._HoSoDKs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblLogin_HoSoDK1", Storage="_HoSoDKs1", ThisKey="IDAccount", OtherKey="IDAccount")]
		public EntitySet<HoSoDK> HoSoDKs1
		{
			get
			{
				return this._HoSoDKs1;
			}
			set
			{
				this._HoSoDKs1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoSoDKs(HoSoDK entity)
		{
			this.SendPropertyChanging();
			entity.tblLogin = this;
		}
		
		private void detach_HoSoDKs(HoSoDK entity)
		{
			this.SendPropertyChanging();
			entity.tblLogin = null;
		}
		
		private void attach_HoSoDKs1(HoSoDK entity)
		{
			this.SendPropertyChanging();
			entity.tblLogin1 = this;
		}
		
		private void detach_HoSoDKs1(HoSoDK entity)
		{
			this.SendPropertyChanging();
			entity.tblLogin1 = null;
		}
	}
}
#pragma warning restore 1591
